### ISSUE TITLE
What is the use of x11-hash-js ?

### ISSUE THREAD

**Issue by dpetrini** [dashpay/x11-hash-js#4]
I see  x11-hash-js in some repositories with bitcore.

I am porting a coin to bitcore, it is working insight app, but I have not used the hash anyway.

So, why need x11 hash in JS?

Sorry for the silly question.

**Comment by nmarley** [comment]
Hi,

The X11 hash is the block hashing (Proof-of-Work) algorithm for Dash. You can verify the block's Proof-of-Work by hashing the raw bytes of the 80-byte block header and verifying that the result is lower than or equal to the target difficulty. In Bitcoin, the equivalent algorithm used is double-sha256.
